apiVersion: apps/v1
kind: Deployment
metadata:
  name: curltool
  labels:
    app: curltool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curltool
  template:
    metadata:
      labels:
        app: curltool
    spec:
      serviceAccountName: default-sa-207-211-161-111
      containers:
        - name: api
          image: registry2.nxgn.space/curltool:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: AUTH_KEY
              value: "GraktongBgNVHSMEGDAWgBQk6FNXXXw0QIep65TbuuEWePwppDBABggrBgEFBQcBAQQ0MDIw"
          resources:  # optional, but good for autoscaling later
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: curltool
  namespace: default
spec:
  selector:
    app: curltool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: curltool-ingress
  namespace: default
spec:
  ingressClassName: traefik
  rules:
    - host: "curltool.nxgn.space"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: curltool
                port:
                  number: 80
  tls:
    - hosts:
        - "curltool.nxgn.space"
      secretName: default-tls
