apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-tool-backend
  labels:
    app: curl-tool-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-tool-backend
  template:
    metadata:
      labels:
        app: curl-tool-backend
    spec:
      containers:
        - name: api
          image: murphyalbert/cookbooks:curl-tool-backend-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:  # optional, but good for autoscaling later
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: curl-tool-backend
spec:
  selector:
    app: curl-tool-backend
  ports:
    - protocol: TCP
      port: 80        # Port exposed inside the cluster
      targetPort: 3000 # Fastify container port
      nodePort: 30050 # External port (VM:30050 → Pod:3000)
  type: NodePort
