# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: curl-tool-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: curl-tool-sa
    namespace: default
roleRef:
  kind: Role
  name: curl-tool-role
  apiGroup: rbac.authorization.k8s.io
