apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: curl-tool-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status", "pods/log"]
    verbs: ["get", "list", "create", "delete", "watch"]
