apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: curl-tool-role
  namespace: default
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - pods/status
      - services
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]
